config/routes.rb
Turismoapp::Application.routes.draw do

  get "dashboard/index", :as => "dashboard"
  get "help/index", :as => "help"
  
  devise_for :users, :path => "auth", :controllers => { :sessions => :sessions, :registrations => :registrations, :confirmations => :confirmations }, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'register_me' }
  
  resources :users  
  resources :groups
  resources :permissions

  resources :customers

  resources :cities
  resources :states
  

  root :to => 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    
    can :manage, :all if user.admin?
    
    #Need to fix it, not a better solution, i dont know why
    user.groups.map(&:permissions).uniq.each do |permission_groups|
      permission_groups.each do |permission|
        can permission.action.to_sym, permission.subject_class.constantize 
      end
    end
  end
  

  #def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  #end
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :capital, :name, :state_id
  
  belongs_to :state
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :hostname, :cnpj

  # Validations
  validates_presence_of :name, :hostname, :name
  validates_uniqueness_of :cnpj

  # Relations
  has_many :users
  has_many :groups
  
  # Brazilian Rails
  usar_como_cnpj :cnpj
end

app/models/group.rb
class Group < ActiveRecord::Base
  # Awesome nested set (Tree)
  acts_as_nested_set
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :customer_id, :parent_id, :user_ids, :permission_ids
  
  # Relations  
  belongs_to :customers
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions
  belongs_to :parent, :class_name => "Group"
  
  # Permissions  
  validates_presence_of :name, :permissions
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_and_belongs_to_many :groups
  
  attr_accessible :name, :action, :subject_class
 
  validates_uniqueness_of :action, :scope => :subject_class
  validates_presence_of :action, :subject_class
  
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :acronym, :name
  
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :confirmable, :lockable, :timeoutable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :nickname, :customer_id, :group_ids, :cpf, :cnpj
  
  # Validations
  validates_presence_of :nickname, :email, :name
  validates_presence_of :cpf, :unless => :cnpj?
  validates_presence_of :cnpj, :unless => :cpf?
  validates_uniqueness_of :cnpj, :unless => :cpf?
  validates_uniqueness_of :cpf, :unless => :cnpj?
  validates_uniqueness_of :email

  # Relations
  belongs_to :customer
  has_and_belongs_to_many :groups
  
  # Brazilian Rails
  usar_como_cpf :cpf
  usar_como_cnpj :cnpj
  
end

app/controllers/cities_controller.rb
class CitiesController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  actions :all
  respond_to :html, :json, :xml
  
  caches_page :index
  
  def index
    @cities = City.includes(:state).all
    super
  end
  
  def update
    update!{cities_url}
  end
  def create
   create!{cities_url}
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  authorize_resource :class => false
  
  def index
    
  end
end

app/controllers/states_controller.rb
class StatesController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  actions :all
  respond_to :html, :json, :xml
  
  caches_page :index
  
  def update
    update!{states_url}
  end
  def create
   create!{states_url}
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  actions :index, :show, :destroy, :edit, :update
  respond_to :html, :json, :xml

  def index
    @users = Customer.find(current_customer.id).users
    super
  end

  def edit
    @groups = Customer.find(current_customer.id).groups.order('lft ASC')
    super
  end

  def update
    update!{users_url}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
  	if user
    	gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    	"http://gravatar.com/avatar/#{gravatar_id}.png?s=39"
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/states/_form.html.erb
<%= simple_form_for @state, :html => { :class => "formee" }  do |f| %>
	
	<div class="in">
			<%= f.input :name %>
			<%= f.input :acronym %>
	</div>
	
  	<!--Form footer begin-->
	<section class="box_footer">
		<div class="grid-12-12">
			<input type="reset" class="right button red" value="Clear" />
			<%= f.button :submit, :class => "right button green" %>
		</div>
		<div class="clear"></div>
	</section>
	<!--Form footer end-->

<% end %>

app/views/states/edit.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Editing state 
			<%= link_to 'Back', states_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/states/index.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			states
			<%= link_to 'New State', new_state_path, :class => "button limegreen small fr" %>
		</div> 
	
		<div class="inside">
			<div class="in">
				
				
				<table cellpadding="0" cellspacing="0" border="0" class="display" id="datatable_1">
					<thead>
						<tr>
													    <th>Name</th>
													    <th>Acronym</th>
														
							<th></th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<% @states.each do |state| %>
						<tr>
						
							<td><%= state.name %></td>
						
							<td><%= state.acronym %></td>
						
						
						<td><%= link_to 'Show', state %></td>
						<td><%= link_to 'Edit', edit_state_path(state) %></td>
						<td><%= link_to 'Destroy', state, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
						</tr>
					<% end %>
					</tbody>
				</table>
				
			</div>
		</div>
		
	</div>
</section>
<!-- ======= .grid_12 - block end ======= -->

app/views/states/new.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Creating state 
			<%= link_to 'Back', states_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/states/show.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			state
			<span class="fr">
				<%= link_to 'Edit', edit_state_path(@state) %> | <%= link_to 'Back', states_path %>
			</span>
		</div>
		
		<div class="inside">
			<!-- formee-->
							<p>
				  	<strong>Name:</strong>
  					<%= @state.name %>
				</p>
							<p>
				  	<strong>Acronym:</strong>
  					<%= @state.acronym %>
				</p>
			
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->