config/routes.rb
Turismoapp::Application.routes.draw do

  get "dashboard/index", :as => "dashboard"
  get "help/index", :as => "help"
  
  devise_for :users, :path => "auth", :controllers => { :sessions => :sessions, :registrations => :registrations, :confirmations => :confirmations }, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'register_me' }
  
  resources :users  
  resources :groups
  resources :permissions

  resources :customers

  resources :cities
  resources :states
  

  root :to => 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    
    can :manage, :all if user.admin?
    
    #Need to fix it, not a better solution, i dont know why
    user.groups.map(&:permissions).uniq.each do |permission_groups|
      permission_groups.each do |permission|
        can permission.action.to_sym, permission.subject_class.constantize 
      end
    end
  end
  

  #def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  #end
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :capital, :name, :state_id
  
  belongs_to :state
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :hostname, :cnpj

  # Validations
  validates_presence_of :name, :hostname, :name
  validates_uniqueness_of :cnpj

  # Relations
  has_many :users
  has_many :groups
  
  # Brazilian Rails
  usar_como_cnpj :cnpj
end

app/models/group.rb
class Group < ActiveRecord::Base
  # Awesome nested set (Tree)
  acts_as_nested_set
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :customer_id, :parent_id, :user_ids, :permission_ids
  
  # Relations  
  belongs_to :customers
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions
  belongs_to :parent, :class_name => "Group"
  
  # Permissions  
  validates_presence_of :name, :permissions
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_and_belongs_to_many :groups
  
  attr_accessible :name, :action, :subject_class
 
  validates_uniqueness_of :action, :scope => :subject_class
  validates_presence_of :action, :subject_class
  
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :acronym, :name
  
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :confirmable, :lockable, :timeoutable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :nickname, :customer_id, :group_ids, :cpf, :cnpj
  
  # Validations
  validates_presence_of :nickname, :email, :name
  validates_presence_of :cpf, :unless => :cnpj?
  validates_presence_of :cnpj, :unless => :cpf?
  validates_uniqueness_of :cnpj, :unless => :cpf?
  validates_uniqueness_of :cpf, :unless => :cnpj?
  validates_uniqueness_of :email

  # Relations
  belongs_to :customer
  has_and_belongs_to_many :groups
  
  # Brazilian Rails
  usar_como_cpf :cpf
  usar_como_cnpj :cnpj
  
end

app/controllers/cities_controller.rb
class CitiesController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  actions :all
  respond_to :html, :json, :xml
  
  caches_page :index
  
  def index
    @cities = City.includes(:state).all
    super
  end
  
  def update
    update!{cities_url}
  end
  def create
   create!{cities_url}
  end
end

app/controllers/groups_controller.rb
class GroupsController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource

  actions :all
  respond_to :html, :json, :xml
  
  def index
    @groups = Customer.find(current_customer.id).groups.order('lft ASC')
    super
  end
  def edit
    @users = Customer.find(current_customer.id).users
    @permissions = Permission.all
    super
  end
  def new
    @users = Customer.find(current_customer.id).users
    @permissions = Permission.all
    super
  end
  def update
    update!{groups_url}
  end
  def create
    params[:group][:customer_id] = current_customer.id
    super do |format|
      format.html { redirect_to groups_url }
    end    
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  authorize_resource :class => false
  
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  actions :index, :show, :destroy, :edit, :update
  respond_to :html, :json, :xml

  def index
    @users = Customer.find(current_customer.id).users
    super
  end

  def edit
    @groups = Customer.find(current_customer.id).groups.order('lft ASC')
    super
  end

  def update
    update!{users_url}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
  	if user
    	gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    	"http://gravatar.com/avatar/#{gravatar_id}.png?s=39"
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<%= simple_form_for @city, :html => { :class => "formee" }  do |f| %>
	
	<div class="in">
			<%= f.input :name %>
			<%= f.input :capital %>
			<%= f.input :state_id %>
	</div>
	
  	<!--Form footer begin-->
	<section class="box_footer">
		<div class="grid-12-12">
			<input type="reset" class="right button red" value="Clear" />
			<%= f.button :submit, :class => "right button green" %>
		</div>
		<div class="clear"></div>
	</section>
	<!--Form footer end-->

<% end %>

app/views/cities/edit.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Editing city 
			<%= link_to 'Back', cities_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/cities/index.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			cities
			<%= link_to 'New City', new_city_path, :class => "button limegreen small fr" %>
		</div> 
	
		<div class="inside">
			<div class="in">
				
				
				<table cellpadding="0" cellspacing="0" border="0" class="display" id="datatable_1">
					<thead>
						<tr>
													    <th>Name</th>
													    <th>Capital</th>
													    <th>State</th>
														
							<th></th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<% @cities.each do |city| %>
						<tr>
						
							<td><%= city.name %></td>
						
							<td><%= city.capital %></td>
						
							<td><%= city.state.name %></td>
						
						
						<td><%= link_to 'Show', city %></td>
						<td><%= link_to 'Edit', edit_city_path(city) %></td>
						<td><%= link_to 'Destroy', city, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
						</tr>
					<% end %>
					</tbody>
				</table>
				
			</div>
		</div>
		
	</div>
</section>
<!-- ======= .grid_12 - block end ======= -->

app/views/cities/new.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Creating city 
			<%= link_to 'Back', cities_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/cities/show.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			city
			<span class="fr">
				<%= link_to 'Edit', edit_city_path(@city) %> | <%= link_to 'Back', cities_path %>
			</span>
		</div>
		
		<div class="inside">
			<!-- formee-->
							<p>
				  	<strong>Name:</strong>
  					<%= @city.name %>
				</p>
							<p>
				  	<strong>Capital:</strong>
  					<%= @city.capital %>
				</p>
							<p>
				  	<strong>State:</strong>
  					<%= @city.state_id %>
				</p>
			
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/groups/_form.html.erb
<%= simple_form_for @group, :html => { :class => "formee" }  do |f| %>
	
	<div class="in">
		<%= f.input :name %>
		<%= f.hidden_field :parent_id, :value => params[:parent_id] || @group.parent_id %>
		
		
		<!-- ======= UI TABS ======= -->
		<div class="ui_tabs">
			<ul>
				<li><a href="#tabs-1">Users</a></li>
				<li><a href="#tabs-2">Permissions</a></li>
			</ul>
			<div id="tabs-1">
				<p>
					<% if @users %>
						<p>
							<%= f.collection_check_boxes :user_ids, @users, :id, lambda {|x| ("#{x[:name]} (#{x[:email]})")}, :item_wrapper_class => 'grid-6-12' %>
						</p>
					<% end %>
				</p>
			</div>
			<div id="tabs-2">
				<p>


				  <% current_permissions_groups.each do |models_names| %>    
				    <div class="control-group">
				      <%= field_set_tag models_names do %>
				        <%# Permission.where(:subject_class => models_names).each do |permission| %>
				          <label class="checkbox">
							<%= f.collection_check_boxes :permission_ids, @permissions.select{|c| c.subject_class == models_names }, :id, lambda {|x| ("#{x[:action]}")}, :item_wrapper_class => 'grid-1-12' %>
				          </label>
				        <%#end%>
				      <%end%>
				    </div>
				  <%end%>


				</p>
			</div>
		</div>
	</div>
	
  	<!--Form footer begin-->
	<section class="box_footer">
		<div class="grid-12-12">
			<input type="reset" class="right button red" value="Clear" />
			<%= f.button :submit, :class => "right button green" %>
		</div>
		<div class="clear"></div>
	</section>
	<!--Form footer end-->

<% end %>

app/views/groups/edit.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Editing group 
			<%= link_to 'Back', groups_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/groups/index.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Groups
			<%= link_to 'New Root Group', new_group_path, :class => "button limegreen small fr" %>
		</div> 
	
		<div class="inside">
			<div class="in">
				
				
				<table cellpadding="0" cellspacing="0" border="0" class="display" id="datatable">
					<thead>
						<tr>
							<th>Name</th>
							<th>Parent</th>
														
							<th></th>
							<th></th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<% Group.each_with_level(@groups) do |group, level| %>
						<tr>
						
						<td style="padding-left: <%= level * 8 %>px;"><%= group.name %></td>
						<td><%= if group.parent then group.parent.name end %></td>
						
						
						<td><%= link_to 'Add Child Group', new_group_path(:parent_id => group) %></td>
						<td><%= link_to 'Show', group %></td>
						<td><%= link_to 'Edit', edit_group_path(group) %></td>
						<td><%= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
						</tr>
					<% end %>
					</tbody>
				</table>
				
			</div>
		</div>
		
	</div>
</section>
<!-- ======= .grid_12 - block end ======= -->

app/views/groups/new.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Creating group 
			<%= link_to 'Back', groups_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/groups/show.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			group
			<span class="fr">
				<%= link_to 'Edit', edit_group_path(@group) %> | <%= link_to 'Back', groups_path %>
			</span>
		</div>
		
		<div class="inside">
			<!-- formee-->
							<p>
				  	<strong>Name:</strong>
  					<%= @group.name %>
				</p>
			
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => "formee" }  do |f| %>
	
	<div class="in">
			<%= f.input :name %>
			<%= f.input :email %>
			<%= f.input :nickname %>

			<!-- ======= UI TABS ======= -->
			<div class="ui_tabs">
				<ul>
					<li><a href="#tabs-1">Groups</a></li>
				</ul>
				<div id="tabs-1">
					<p>
						<% if @groups %>
							<p>
								<%= f.collection_check_boxes :group_ids, @groups, :id, lambda {|x| ("#{'--' * x.level} #{x[:name]}")}, :item_wrapper_class => "block" %>
							</p>
						<% end %>
					</p>
				</div>
			</div>
	</div>

	
  	<!--Form footer begin-->
	<section class="box_footer">
		<div class="grid-12-12">
			<input type="reset" class="right button red" value="Clear" />
			<%= f.button :submit, :class => "right button green" %>
		</div>
		<div class="clear"></div>
	</section>
	<!--Form footer end-->

<% end %>

app/views/users/edit.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Editing User 
			<%= link_to 'Back', customers_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/users/index.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Users
			<%= link_to "New User", new_user_path, :class => "button limegreen small fr" %>
		</div> 
	
		<div class="inside">
			<div class="in">
				
				
				<table cellpadding="0" cellspacing="0" border="0" class="display" id="datatable_1">
					<thead>
						<tr>
					    	<th>Full Name</th>
						  	<th>Email</th>
						  	<th>Username</th>
						  	<th>Admin?</th>
						  	<th>Customer</th>
							<th>Active?</th>
					    	<th></th>
					    	<th></th>
					    	<th></th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td><%=h user.name %></td>
							<td><%=h user.email %></td>
							<td><%=h user.nickname %></td>
							<td>
								<% if user.admin? %>	
									<%= link_to "Active Admin", confirmation_url(user, :confirmation_token => user.confirmation_token) %>
								<% else %>
									Active
								<% end %>
							</td>
							<td><%=h user.customer.name %></td>
							
							<td>
								<% if user.confirmation_token %>	
									<%= link_to "Active Now", confirmation_url(user, :confirmation_token => user.confirmation_token) %>
								<% else %>
									Active
								<% end %>
							</td>
															  
							<td><%= link_to 'Show', user %></td>
							<td><%= link_to 'Edit', edit_user_path(user) %></td>
							<td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
				
			</div>
		</div>
		
	</div>
</section>
<!-- ======= .grid_12 - block end ======= -->

app/views/users/new.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			Creating admin_webserver 
			<%= link_to 'Back', admin_webservers_path, :class => "fr" %>
		</div>
		
		<div class="inside">
			<!-- formee-->
				<%= render 'form' %>
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<!-- ======= .grid_12 - block begin ======= -->
<section class="grid_12">
	<div class="box">
		<div class="title"><span class="icon16_sprite i_network_monitor"></span>
			admin_webserver
			<span class="fr">
				<%= link_to 'Edit', edit_admin_webserver_path(@admin_webserver) %> | <%= link_to 'Back', admin_webservers_path %>
			</span>
		</div>
		
		<div class="inside">
			<!-- formee-->
							<p>
				  	<strong>Name:</strong>
  					<%= @admin_webserver.name %>
				</p>
			
			<!-- formee-->
		</div>
	</div>
</section>
<div class="clear"></div>
<!-- ======= .grid_12 - block end ======= -->