config/routes.rb
Turismoapp::Application.routes.draw do

  get "dashboard/index", :as => "dashboard"
  get "help/index", :as => "help"
  
  devise_for :users, :path => "auth", :controllers => { :sessions => :sessions, :registrations => :registrations, :confirmations => :confirmations }, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'register_me' }
  
  resources :users  
  resources :groups
  resources :permissions

  resources :customers

  resources :cities
  resources :states
  

  root :to => 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    
    can :manage, :all if user.admin?
    
    #Need to fix it, not a better solution, i dont know why
    user.groups.map(&:permissions).uniq.each do |permission_groups|
      permission_groups.each do |permission|
        can permission.action.to_sym, permission.subject_class.constantize 
      end
    end
  end
  

  #def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  #end
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :capital, :name, :state_id
  
  belongs_to :state
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :hostname, :cnpj

  # Validations
  validates_presence_of :name, :hostname, :name
  validates_uniqueness_of :cnpj

  # Relations
  has_many :users
  has_many :groups
  
  # Brazilian Rails
  usar_como_cnpj :cnpj
end

app/models/group.rb
class Group < ActiveRecord::Base
  # Awesome nested set (Tree)
  acts_as_nested_set
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :customer_id, :parent_id, :user_ids, :permission_ids
  
  # Relations  
  belongs_to :customers
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions
  belongs_to :parent, :class_name => "Group"
  
  # Permissions  
  validates_presence_of :name, :permissions
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_and_belongs_to_many :groups
  
  attr_accessible :name, :action, :subject_class
 
  validates_uniqueness_of :action, :scope => :subject_class
  validates_presence_of :action, :subject_class
  
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :acronym, :name
  
  has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :confirmable, :lockable, :timeoutable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :nickname, :customer_id, :group_ids, :cpf, :cnpj
  
  # Validations
  validates_presence_of :nickname, :email, :name
  validates_presence_of :cpf, :unless => :cnpj?
  validates_presence_of :cnpj, :unless => :cpf?
  validates_uniqueness_of :cnpj, :unless => :cpf?
  validates_uniqueness_of :cpf, :unless => :cnpj?
  validates_uniqueness_of :email

  # Relations
  belongs_to :customer
  has_and_belongs_to_many :groups
  
  # Brazilian Rails
  usar_como_cpf :cpf
  usar_como_cnpj :cnpj
  
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  authorize_resource :class => false
  
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  actions :index, :show, :destroy, :edit, :update
  respond_to :html, :json, :xml

  def index
    @users = Customer.find(current_customer.id).users
    super
  end

  def edit
    @groups = Customer.find(current_customer.id).groups.order('lft ASC')
    super
  end

  def update
    update!{users_url}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
  	if user
    	gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    	"http://gravatar.com/avatar/#{gravatar_id}.png?s=39"
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<%= csrf_meta_tags %>

		<title>Turismo App | <%= current_customer.name %></title>

		<!-- ====================================================================================
		STYLES BEGIN
		===================================================================================== -->

		<%= stylesheet_link_tag "application", :media => "all" %>

		<%= stylesheet_link_tag "reset", :media => "all" %>
		<%= stylesheet_link_tag "grid", :media => "all" %>
		<%= stylesheet_link_tag "config", :media => "all" %>
		<%= stylesheet_link_tag "plugin_config", :media => "all" %>

		<!-- ======================================================================================
		SCRIPTS BEGIN
		======================================================================================= -->

		<%= javascript_include_tag "application" %>

		<%= javascript_include_tag "global_plugins_scripts" %>
		<%= javascript_include_tag "../plugins/lightbox/js/lightbox/jquery.lightbox.min" %>

		<%= javascript_include_tag "../plugins/jqueryui/all/jquery-ui-1.8.16.custom.min" %>
		<%= javascript_include_tag "../plugins/validator/js/languages/jquery.validationEngine-en" %>
		<%= javascript_include_tag "../plugins/validator/js/jquery.validationEngine" %>
		<%= javascript_include_tag "../plugins/dialogs/jquery-fallr-1.2" %>
		<%= javascript_include_tag "../plugins/tinymce/jscripts/tiny_mce/jquery.tinymce" %>
		<%= javascript_include_tag "../plugins/spin/jquery-spin" %>
		<%= javascript_include_tag "../plugins/qtip/jquery.qtip.min" %>
		<%= javascript_include_tag "../plugins/plupload/js/browserplus-min" %>
		<%= javascript_include_tag "../plugins/plupload/js/plupload.full" %>
		<%= javascript_include_tag "../plugins/plupload/js/jquery.plupload.queue/jquery.plupload.queue" %>
		<%= javascript_include_tag "../plugins/multiselect/js/ui.multiselect" %>
		<%= javascript_include_tag "../plugins/datatables/media/js/jquery.dataTables" %>
		<%= javascript_include_tag "../plugins/alerts/javascript/jquery.toastmessage" %>
		<%= javascript_include_tag "../plugins/prettify/prettify" %>
		<%= javascript_include_tag "../plugins/fullcalendar/fullcalendar.min" %>
		<%= javascript_include_tag "../plugins/fileexplorer/js/elfinder.min" %>

		<!--<%= javascript_include_tag "../plugins/fileexplorer/js/i18n/elfinder.ru" %>-->
		<!-- Flotr2 Charts -->
		<%= javascript_include_tag "../plugins/flotr2/flotr2.min" %>
		<!--[if IE 8]><%= javascript_include_tag "../plugins/flotr2/flotr2.ie.min" %><![endif]-->

		<!-- color picker -->
		<%= javascript_include_tag "../plugins/colorpicker/js/colorpicker" %>
		<%= javascript_include_tag "../plugins/colorpicker/js/eye" %>
		<%= javascript_include_tag "../plugins/colorpicker/js/utils" %>
		<%= javascript_include_tag "../plugins/colorpicker/js/layout" %>

		<!-- = From JS Dir -->
		<%= javascript_include_tag "modernizr.custom" %>
		<%= javascript_include_tag "jquery.autogrowtextarea" %>
		<%= javascript_include_tag "jquery.autotab-1.1b" %>

		<!-- From JS Dir [plugin initialization] -->
		<%= javascript_include_tag "dialog_fallr_init" %>
		<%= javascript_include_tag "tiny_mce_init" %>
		<%= javascript_include_tag "datatables_init" %>
		<%= javascript_include_tag "head_scripts" %>

	</head>
	<body>

		<section id="layout">

			<div class="logo_profile container_12">

				<div class="grid_6 logo_img">
					<%= current_customer.name %>		
				</div>
				<div class="grid_6 profile_meta">
					<div class="user_meta">
						<div>
							<%= image_tag avatar_url(current_user), :alt => "gravatar.com" %>
						</div>
						<div class="name">
							<% if current_user %>
							    <strong> <%= current_user.nickname %> </strong> (<%= current_user.email %>)
								<br>
								<%= link_to :Edit, edit_user_registration_path(current_user), :class => "submeta" %>  <%= link_to 'Logout', destroy_user_session_path, :class => "submeta" %>
							<% else %>
								You're not logged in, <%= link_to 'Login', new_user_session_path %>
							<% end %>
						</div>
					</div>
				</div>

				<div class="clear"></div>
			</div>

			<section id="top">

				<section id="top_bar">
					<section id="main_menu">
						<ul class="sf-menu">
							<li>
								<%= link_to :Dashboard, dashboard_path %>
							</li>
							<li>
								<a href="#">Hotéis</a>
								<ul>
									<li>
										<a href="form_elements.html">Buscar</a>
									</li>
									<li>
										<a href="user_interface.html">Administrar</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="#">Destinos</a>
								<ul>
									<li>
										<a href="charts.html">Buscar</a>
									</li>
									<li>
										<a href="datatables.html">Administrar</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="#">Aéreo</a>
								<ul>
									<li>
										<a href="charts.html">Buscar</a>
									</li>
									<li>
										<a href="datatables.html">Administrar</a>
									</li>
								</ul>
							</li>
							
							<li>
								<a href="#">Administration</a>
								<ul>
									<% if current_user.admin? %>
									<li>
										<%= link_to :Customers, customers_path if can? :index, Customer %>
									</li>
									<% end %>
									<li>
										<%= link_to :Groups, groups_path if can? :index, Group %>
									</li>
									<li>
										<%= link_to :Users, users_path if can? :index, User %>
									</li>
									<li>
										<a href="#">Supply (Others)</a>
										<ul>
											<li>
												<%= link_to :States, states_path if can? :index, State %>
											</li>
											<li>
												<%= link_to :Cities, cities_path if can? :index, City %>
											</li>
										</ul>
									</li>
								</ul>
							</li>
							
							<li>
								<%= link_to :Help, help_path %>
							</li>
						</ul>
						<div class="clear"></div>
					</section><!-- End of #main_menu -->
				</section><!-- End of #top_bar -->
				<div class="clear"></div>

				<section class="top_in">
					<section id="second_top_bar">
						<div id="quick_task" class="jThumbnailScroller">
							<div class="jTscrollerContainer">
								<div class="clear"></div>
								<ul class="jTscroller">
									<li>
										<%= link_to "<span class='icon1'></span>".html_safe + "Dashboard", dashboard_path %>
									</li>
									<li>
										<%= link_to "<span class='icon3'></span>".html_safe + :Relatórios, dashboard_path %>
									</li>
									<li>
										<%= link_to "<span class='icon4'></span>".html_safe + :Reservas, dashboard_path %>
									</li>
									<li>
										<%= link_to "<span class='icon2'></span>".html_safe + :Agenda, dashboard_path %>
									</li>
									<li>
										<%= link_to "<span class='icon9'></span>".html_safe + :Users, users_path if can? :index, User %>
									</li>
									<li>
										<%= link_to "<span class='icon19'></span>".html_safe + :Groups, groups_path if can? :index, Group %>
									</li>
									<li>
										<%= link_to "<span class='icon6'></span>".html_safe + :Customers, customers_path if can? :index, Customer %>
									</li>
									
								</ul>
								<div class="clear"></div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</section><!-- End of #second_top_bar -->
				</section><!-- End of .top_in -->

			</section><!-- End of #top -->

			<section id="container" class="container_12">
				<% if notice %>
					<script>
						$(function() { 
							showSucessToast('<%= notice %>');	
						});
					</script>
				<% end %>
				
				<% if alert %>
					<div class="alert error_msg"><span class="alert_close"></span> <%= alert %> </div>
				<% end %>
				
				<%= yield %>
				
			</section><!-- End of #container -->

		</section><!-- End of #layout -->
		<div class="clear"></div>
		
		<!-- Bottom Scripts -->
		<%= javascript_include_tag "jqueryui_init" %>
		<%= javascript_include_tag "flotr2_init" %>
		<%= javascript_include_tag "bottom_scripts" %>
		<%= javascript_include_tag "custom_pages" %>
		<%= javascript_include_tag "jquery.thumbnailScroller" %>

	</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<%= csrf_meta_tags %>

		<title>Turismo App | <%= current_customer.name %></title>

		<!-- ====================================================================================
		STYLES BEGIN
		===================================================================================== -->

		<%= stylesheet_link_tag "application", :media => "all" %>

		<%= stylesheet_link_tag "reset", :media => "all" %>
		<%= stylesheet_link_tag "grid", :media => "all" %>
		<%= stylesheet_link_tag "config", :media => "all" %>
		<%= stylesheet_link_tag "plugin_config", :media => "all" %>

		<!-- ======================================================================================
		SCRIPTS BEGIN
		======================================================================================= -->

		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag "global_plugins_scripts" %>
		


	</head>
	<body>

		<section id="layout" style="width: 50%; margin-top: 100px">

			<section id="container" class="container_12">
				<% if notice %>
					<script>
						$(function() { 
							showSucessToast('<%= notice %>');	
						});
					</script>
				<% end %>
				
				<% if alert %>
					<div class="alert error_msg"><span class="alert_close"></span> <%= alert %> </div>
				<% end %>
				
				<%= yield %>
				
			</section><!-- End of #container -->

		</section><!-- End of #layout -->
		<div class="clear"></div>


		<!-- Bottom Scripts -->
		<%= javascript_include_tag "bottom_scripts" %>
		
	</body>
</html>